server:
  port: 9000

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/

zuul:
  prefix: /coupon
  routes:
    template:
      path: /template/**
      serviceId: eureka-client-template
      strip-prefix: false
    distribution:
      path: /distribution/**
      serviceId: eureka-client-distribution
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000